SHOW DATABASES;

USE `rafael-auth-lab`;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  passwd VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM users;	
TRUNCATE TABLE users;

CREATE TABLE otp_codes (
	id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    otp INT,
    expires_at TIMESTAMP 
);
SELECT * FROM otp_codes;
TRUNCATE TABLE otp_codes;